### ISSUE TITLE
How do you get a game running?

### ISSUE THREAD

**Issue by JustinLee27** [alexhkurz/BlocklyPrisonersDilemma#2]
I wanted to know how to get two instances of the game running so I can have two players and play the game?

**Comment by alexhkurz** [comment]
One thing you need to know is that the second player needs to run in another browser or in a private/incognito tab. The reason is that each player needs its own session and the session id is stored as a cookie in the browser. If you just open a new tab for the second player, then both players/tabs will be in the same session.
